### ISSUE TITLE
Getting bounding box with matrix transforms

### ISSUE THREAD

**Issue by Jaydee2190** [libnui/nui3#15] opened 2011-01-27 19:26 UTC
Let's say i've got a widget with a nuiMatrixNode_Scale matrix, and i've set this to be 0.5,0.5,1 scaling

GetIdealRect returns {240,720,160,480} (the widget is in a nuiFixed container)
Then LocalToGlobal on this rect then shows me 120,360,80,240 (it scaled properly, however the x origin is wrong).  It should all be shifted to 240.  Is it because i'm using userPos?  If I happen to have a pivot matrix with an origin set then these numbers go haywire.

Ultimately I need...given a widget with a bunch of matrixes assigned to it, a way to get the Bounding Rect in "real" dimensions (even if its rotated).  Looks like its all the localToGlobal functions that only use the matrix transforms, but its not quite working for me

This appears to work(kind of, if I want content bounds i'll need to adjust my left and right positions to userpos)

nuiRect localRect=proxy->GetIdealRect();
    if (!proxy->IsMatrixIdentity())
    {
        nuiMatrix matrix=proxy->GetMatrix();
        nuiVector vec1(localRect.mLeft,localRect.mTop,0);
        nuiVector vec2(localRect.mRight,localRect.mBottom,0);
        vec1 = matrix \* vec1;
        vec2 = matrix \* vec2;

```
    localRect.mLeft   = vec1[0];
    localRect.mTop    = vec1[1];
    localRect.mRight  = vec2[0];
    localRect.mBottom = vec2[1];

}
return abs(localRect.GetWidth());
```

Generally speaking I find all the rects terrible confusing!

**Comment by Jaydee2190** [comment] 2011-01-27 19:41
Here's another example.

IdealRect brings back
{240,720,160,480} , using the matrix multiplication code from above i'm rotating around the centre of the object 90 degrees, my matrix is {-4.3711388e-08,1,0,0,-1,-4.3711388e-08,0,0,0,0}

after the vectors get multipled by the matrix i get
vec1=0,0,0,1
vec2=-320,480,0,1

which then gives me a rect of
L:0
R:-320
T:0
B:480

Why the -320 for the Right attribute? (I get the same when I just use LocalToGlobal

**Comment by meeloo** [comment] 2011-01-27 21:30
Hi Jaydee,

I had to read this one a few times before understanding what was going wrong (I'm not yet sure I have the answer to all your questions yet, you'll tell me :-) ).

Widget coordinates is a complex matter. What makes it very complex is that nuiWidget methods use different origins: some are local (0,0 means the top left of the widget's contents), some are relative to the widget's parent (0,0 is the top left of the parents contents). some are global (0,0 is the top left of the top level container). I think that may the root of the issues you are experiencing.

What uses Local origin:
X and Y in Mouse events (and Drag and Drop events).
Draw operations.
Set/GetVisibleRect
Set/GetHotRect
InvalidateRect
LocalToLocal -> from this widget's local origin to the referenced widget local origin.
GlobalToLocal -> from global origin (the nuiTopLevel that is the root of the tree) to local.
LocalToGlobal -> the opposite of GlobalToLocal.

However, Layout operations expect coordinates that relative to the **parent**:
GetIdealRect
SetLayout
SetRect
GetRect
GetBorderedRect
Set/GetUser[Width|Height|Top|LeftRight|Bottom|Rect|Pos](yeah, quite a mouthfull...)

The matrix operations always work on strictly local coordinates. This means that if you feed them the result of GetRect without first doing a LocalToLocal(GetParent(), rect); the result will be wrong, unless the widget is placed on the top left corner of its parent.

In the case you describe this is exactly what I think happens: GetIdealRect usually returns a rectangle that looks like {0, 0, idealwidth, idealheight} which would be a fine rectangle to pass to the matrix operations. **BUT**, as soon as you give your widget a User position, GetIdealRect returns { UserX, UserY, IdealWidth, IdealHeight }, that's the way the parent knows there is something special to do for this widget. You should always consider the return value of GetIdealRect to be local to the parent, and possibly not laying down on it 0,0 (top left) corner. That is even more true if the parent is an nuiFixed.

Last but not least, the pivot and rotation matrices will mess up your rects and it has two consequences:
- it breaks clipping as we don't support clipping rects that are not parallels to the OpenGL context's borders (we use glScissor). It is manageable by disabling clipping on the widget you want to rotate and is should stay manageable once you know about it.
- to calculate your bounding rect you will have to transform all four corners of the original rect as the rotated rect will not be parallel to the axes. Once more this is easy to do, however there is no method in nui to do it for you.

I hope these explanations will help you. do not hesitate ask for more. Also, I may have made errors so feel free to tell me if what I said can't explain your empirical evidence :-).

I'm going to create a new wiki page with the content of this issue and try to make the documentation in nuiWidget.h more explicit.

Thanks,

S.

**Comment by Jaydee2190** [comment] 2011-01-27 21:47
Amazing help!  Yea, I think that does help me out, and I ran into autoclip already! i'll try it all tomorrow.

You said though...
- to calculate your bounding rect you will have to transform all four corners of the original rect as the rotated rect will not be parallel to the axes. Once more this is easy to do, however there is no method in nui to do it for you.

You wouldn't happen to have such piece of code lying around would you? ;)

Also, this is a bit minor but at least on the iphone simulator..

void MainWindow::OnCreation()
{
  nuiFixed\* pBox = new nuiFixed();

  AddChild(pBox);

```
nuiButton *aButton=new nuiButton(_T("Click test"));
aButton->AddMatrixNode(new nuiMatrixNode_Translation(100,150,0));
aButton->AddMatrixNode(new nuiMatrixNode_Pivot(20,-20,-20,0,0,0,1));
aButton->AddMatrixNode(new nuiMatrixNode_Scale(3.0,3.0,1.0));

 aButton->SetAutoClip(false);
pBox->AddChild(aButton);
```

}

Clicking on the button a few times, sometimes it gets stuck in a dirty state(the rect seems to not be aligned to the transformation axis)

**Comment by Jaydee2190** [comment] 2011-01-27 22:01
Hmmm,... 90 degree transformation
rect = {240,720,160,480}
proxy->LocalToLocal(proxy->GetParent(), rect); 

Gives me - note the '-' value for my right parameter..  Is this the "parallel to the axes" you mentioned [it's "flipped?"]

Ultimately I have any number of widgets, I'd like to get their bounds after any transformations so I can resize my container properly(just as you do with nuiFixed) (so this above along with MoveTo and the userPos should help me there.

Content bounds for a widget in Global /Screen co-ordinates would be great to know if a widget has gone off screen

**Comment by meeloo** [comment] 2011-01-27 23:21
I think you have to reverse your call:
proxy->GetParent()->LocalToLocal(proxy, rect);

as the doc in the header says:
void LocalToLocal(nuiWidgetPtr pWidget, nuiRect& rRect) const; ///< This method translates rRect from the Local coordinate system of this object to the local coordinate system of pWidget. They must be both owned by the same top level object.

To get the actual bounding box of a rotated widget and taking account of its matrix I would start with the code in nuiWidget::LocalToGlobal:

```
nuiVector vec1(rRect.mLeft,rRect.mTop,0);
nuiVector vec2(rRect.mRight,rRect.mBottom,0);
vec1 = GetMatrix() * vec1;
vec2 = GetMatrix() * vec2;
rRect.mLeft   = vec1[0];
rRect.mTop    = vec1[1];
rRect.mRight  = vec2[0];
rRect.mBottom = vec2[1];
```

And modify it that way:
    nuiVector vec1(rRect.mLeft,rRect.mTop,0);
    nuiVector vec2(rRect.mRight,rRect.mTop,0);
    nuiVector vec3(rRect.mRight,rRect.mBottom,0);
    nuiVector vec4(rRect.mLeft,rRect.mBottom,0);
    vec1 = GetMatrix() \* vec1;
    vec2 = GetMatrix() \* vec2;
    vec3 = GetMatrix() \* vec3;
    vec4 = GetMatrix() \* vec4;
    rRect.mLeft   = MIN(vec1[0], MIN(vec2[0], MIN(vec3[0], vec4[0]) ) );
    rRect.mTop    = MIN(vec1[1], MIN(vec2[1], MIN(vec3[1], vec4[1]) ) );
    rRect.mRight  = MAX(vec1[0], MAX(vec2[0], MAX(vec3[0], vec4[0]) ) );
    rRect.mBottom = MAX(vec1[1], MAX(vec2[1], MAX(vec3[1], vec4[1]) ) );

rRect should then contain the smallest rectangle that contains the rotated widget and that is aligned with the screen borders.

Is that what you are looking for?

I'm going to have a look at the broken rotated button example later, could you open a separate issue about it with, possibly a screenshot? Many thanks in advance!

Cheers,

S.

**Comment by meeloo** [comment] 2011-01-27 23:36
Ok, I have looked into the rotated button bug and I fixed it by injecting the exact code I gave you to compute the global rect of a rotated widget so I killed two birds with one stone:
- I can confirm that that code works :-)
- the bug is fixed

I'm closing this issue, please reopen it if you find it is not fixed.

S.

**Comment by Jaydee2190** [comment] 2011-01-28 00:37
Thanks for your help so far, i know you are terribly busy.  I'm just about to jump off a bridge on this!

I've modded LayoutAnimation_iphone using this...

void MainWindow::OnCreation()
{
    nuiImage\* pBgR = new nuiImage(_T("rsrc:/decorations/background.png"));
    pBgR->AddMatrixNode(new nuiMatrixNode_Translation(0,0,0));
    nuiRect textureRect(pBgR->GetTextureRect());
    pBgR->AddMatrixNode(new nuiMatrixNode_Pivot(90,-textureRect.GetWidth()/2,-textureRect.GetHeight()/2,0,0,0,1));
    pBgR->AddMatrixNode(new nuiMatrixNode_Scale(1.0,1.0,1.0));
    pBgR->SetAutoClip(false);

```
AddChild(pBgR);
nuiRect idealRect=pBgR->GetIdealRect();
pBgR->GetParent()->LocalToLocal(pBgR, idealRect); // Co-ords relative to this container with matrix applied
LocalToGlobal(idealRect); // Screen Co-ords?
NGL_OUT(L"Hmmmm");
```

}

Now at some point I expect mLeft and mTop to be negative numbers as the image starts off screen (top left)... it seems to have gotten the dimension correct, so not the origin at all...

I know this as ContentBounds in screen co-ords but I can't figure it out!  (This is a simple 90 degree transform, i'll incorporate your matrix operations once I make it that far!)

**Closed as completed** 2011-01-28 07:36 UTC
